-- 22_timeline_events.sql
--
-- Purpose:
--   Case-wide structured timeline: 1939-present, filterable by category,
--   entity, topic, and importance. Backs a future /timeline UI surface
--   (Phase 3-F) and can also drive a "What\'s new" strip on the home
--   page (category=\'release\').
--
-- Categories:
--   biographical  — Oswald / Ruby / other principal life events
--   operational   — Cold War context, CIA operations, motorcade
--   investigation — Warren Commission, HSCA, ARRB, Church Committee
--   release       — public document releases and milestones
--   death         — deaths of witnesses / principal figures (neutral)
--
-- Importance 1-5 used for zoom-level filtering:
--   5 = headline (Nov 22 assassination, Ruby shoots Oswald, WC published)
--   4 = major (pre-1963 Oswald life events, HSCA established, 2025 release)
--   3 = notable (Cold War context, witness testimony milestones)
--   2 = detail (hour-by-hour granularity, supporting operations)
--   1 = reference (minor releases, secondary investigation steps)
--
-- Dependencies: (none — curated data)

create or replace table jfk_curated.timeline_events as
select * from unnest([
  struct<
    event_id             string,
    event_date           date,
    event_time_local     string,
    title                string,
    description          string,
    category             string,
    related_entity_ids   array<string>,
    related_topic_ids    array<string>,
    source_external      array<string>,
    importance           int64
  >(
    'tl-1939-10-18-oswald-born', date '1939-10-18', null,
    'Lee Harvey Oswald born',
    'Born at Old French Hospital, New Orleans, to Marguerite Claverie Oswald.',
    'biographical', ['oswald'], [],
    ['https://www.archives.gov/research/jfk/warren-commission-report/appendix-13.html'], 4
  ),
  ('tl-1947-09-18-cia-founded', date '1947-09-18', null,
   'Central Intelligence Agency established',
   'CIA established under the National Security Act of 1947, consolidating the postwar intelligence function under a single civilian agency.',
   'operational', ['cia'], [], [], 3),
  ('tl-1956-10-24-oswald-enlists', date '1956-10-24', null,
   'Oswald enlists in the U.S. Marine Corps',
   'Enlists in Dallas at age 17; reports to Marine Corps Recruit Depot, San Diego, on October 26, 1956.',
   'biographical', ['oswald'], [], [], 3),
  ('tl-1959-10-31-oswald-moscow', date '1959-10-31', null,
   'Oswald declares intent to defect',
   'Appears at the U.S. Embassy in Moscow and declares his intent to renounce U.S. citizenship. The CIA opens a 201 personality file on Oswald the following December.',
   'biographical', ['oswald','cia'], ['cia'], [], 4),
  ('tl-1961-04-17-bay-of-pigs', date '1961-04-17', null,
   'Bay of Pigs invasion begins',
   'The CIA-directed Brigade 2506 lands at Playa Girón, Cuba. The operation fails within three days, reshaping Kennedy-CIA relations and U.S. policy toward Castro.',
   'operational', ['cia'], ['cuba'], [], 4),
  ('tl-1961-04-30-oswald-marries', date '1961-04-30', null,
   'Oswald marries Marina Prusakova',
   'Marries in Minsk, Belorussian SSR. Their first daughter, June, is born February 15, 1962.',
   'biographical', ['oswald','marina-oswald'], [], [], 2),
  ('tl-1962-06-13-oswald-returns', date '1962-06-13', null,
   'Oswald returns to the United States',
   'Arrives in New York with Marina and infant daughter June. Interviewed at Idlewild Airport by the FBI. Settles first in Fort Worth, then Dallas.',
   'biographical', ['oswald','marina-oswald','fbi'], [], [], 4),
  ('tl-1962-10-16-cuban-missile-crisis', date '1962-10-16', null,
   'Cuban Missile Crisis begins',
   'U.S. intelligence confirms Soviet medium-range ballistic missiles in Cuba. Thirteen-day standoff shapes the operational context for much of the following year\'s CIA-Cuba planning.',
   'operational', ['cia'], ['cuba'], [], 3),
  ('tl-1963-04-10-walker-shooting', date '1963-04-10', null,
   'Alleged shooting at Gen. Walker\'s residence',
   'A rifle shot is fired through the dining-room window of Major General Edwin A. Walker\'s Dallas home. Warren Commission and ARRB records attribute the shot to Oswald.',
   'biographical', ['oswald'], [], [], 3),
  ('tl-1963-09-27-oswald-mexico-city', date '1963-09-27', null,
   'Oswald visits Mexico City',
   'Travels to Mexico City; visits the Cuban Consulate and the Soviet Embassy through October 2. CIA station cables record the contact; no visa is issued.',
   'biographical', ['oswald','cia'], ['mexico-city','cia','cuba'], [], 5),
  ('tl-1963-10-16-oswald-tsbd', date '1963-10-16', null,
   'Oswald hired at Texas School Book Depository',
   'Begins work as a $1.25/hour order filler at the TSBD building at Elm and Houston in Dallas.',
   'biographical', ['oswald'], [], [], 3),
  ('tl-1963-11-18-motorcade-published', date '1963-11-18', null,
   'Dallas motorcade route published',
   'The Dallas Times Herald publishes the presidential motorcade route; the Dallas Morning News publishes it the following day (November 19). Route is public 72 hours before the motorcade.',
   'operational', ['warren-commission'], [], [], 3),
  ('tl-1963-11-22-air-force-one-dallas', date '1963-11-22', '11:40 a.m. CST',
   'Air Force One lands at Love Field',
   'President Kennedy, Mrs. Kennedy, Vice President Johnson, Governor Connally, and staff arrive at Dallas Love Field.',
   'operational', [], [], [], 3),
  ('tl-1963-11-22-motorcade-departs', date '1963-11-22', '11:55 a.m. CST',
   'Motorcade departs Love Field',
   'Ten-car presidential motorcade departs Love Field for the Trade Mart via Main Street, Houston Street, and Elm Street through Dealey Plaza.',
   'operational', [], [], [], 4),
  ('tl-1963-11-22-shots-fired', date '1963-11-22', '12:30 p.m. CST',
   'Shots fired in Dealey Plaza',
   'Three shots are fired at the presidential motorcade as it passes the Texas School Book Depository. President Kennedy is fatally wounded; Governor Connally is seriously wounded; bystander James Tague sustains a minor injury from a bullet or fragment striking the curb of Main Street.',
   'operational', ['oswald','warren-commission'], [], [], 5),
  ('tl-1963-11-22-parkland-1pm', date '1963-11-22', '1:00 p.m. CST',
   'JFK pronounced dead at Parkland Hospital',
   'President Kennedy is pronounced dead at Parkland Memorial Hospital. Governor Connally survives his wounds.',
   'operational', [], [], [], 5),
  ('tl-1963-11-22-tippit', date '1963-11-22', '1:15 p.m. CST',
   'Murder of Officer J. D. Tippit',
   'Dallas Police Officer J. D. Tippit is shot and killed at East 10th Street and Patton Avenue in Oak Cliff. Nine eyewitnesses later identify Oswald as the gunman.',
   'operational', ['oswald','tippit'], [], [], 5),
  ('tl-1963-11-22-theatre-arrest', date '1963-11-22', '1:50 p.m. CST',
   'Oswald arrested at the Texas Theatre',
   'Dallas Police arrest Lee Harvey Oswald inside the Texas Theatre, 231 West Jefferson Boulevard, Oak Cliff. He is charged with the Tippit murder the same evening, and with the Kennedy assassination later that night.',
   'operational', ['oswald','tippit'], [], [], 5),
  ('tl-1963-11-22-lbj-sworn', date '1963-11-22', '2:38 p.m. CST',
   'Lyndon Johnson sworn in as President',
   'Aboard Air Force One at Love Field, Judge Sarah T. Hughes administers the oath of office to Vice President Lyndon B. Johnson.',
   'operational', [], [], [], 4),
  ('tl-1963-11-22-amlash-paris', date '1963-11-22', null,
   'CIA/AMLASH meeting in Paris',
   'CIA case officer Nestor Sanchez meets Rolando Cubela (AMLASH-1) in Paris and passes him a poison pen; the meeting, centered on a plot against Fidel Castro, is taking place as the assassination of President Kennedy occurs in Dallas. Documented in the Church Committee record.',
   'operational', ['cia'], ['cia','cuba'],
   ['https://www.intelligence.senate.gov/resources/intelligence-related-commissions'], 3),
  ('tl-1963-11-23-backyard-photos', date '1963-11-23', null,
   'Marina Oswald identifies backyard photographs',
   'Marina Oswald is shown the CE-133 backyard photographs and testifies that she took them in the backyard of the Neely Street residence in late March or early April 1963.',
   'investigation', ['oswald','marina-oswald'], [], [], 3),
  ('tl-1963-11-24-ruby-shoots-oswald', date '1963-11-24', '11:21 a.m. CST',
   'Jack Ruby shoots Lee Harvey Oswald',
   'During a jail transfer in the basement of Dallas Police Headquarters, Jack Ruby steps forward and fires a single round from a .38 Smith & Wesson into Oswald\'s abdomen.',
   'operational', ['oswald','ruby'], [], [], 5),
  ('tl-1963-11-24-oswald-dies', date '1963-11-24', '1:07 p.m. CST',
   'Oswald pronounced dead at Parkland',
   'Lee Harvey Oswald is pronounced dead at Parkland Memorial Hospital, the same hospital where President Kennedy was pronounced dead 47 hours earlier.',
   'operational', ['oswald'], [], [], 5),
  ('tl-1963-11-25-jfk-funeral', date '1963-11-25', null,
   'State funeral and burial of President Kennedy',
   'The state funeral procession passes from the White House to St. Matthew\'s Cathedral, followed by burial at Arlington National Cemetery.',
   'operational', [], [], [], 4),
  ('tl-1963-11-29-wc-established', date '1963-11-29', null,
   'Warren Commission established',
   'President Lyndon B. Johnson issues Executive Order 11130 establishing the President\'s Commission on the Assassination of President Kennedy, chaired by Chief Justice Earl Warren.',
   'investigation', ['warren-commission'], ['warren-commission'],
   ['https://www.archives.gov/research/jfk/warren-commission-report'], 5),
  ('tl-1964-02-03-wc-marina-testimony', date '1964-02-03', null,
   'Warren Commission hearings begin',
   'The Warren Commission begins taking sworn testimony. Marina Oswald is the first witness, appearing February 3-6, 1964.',
   'investigation', ['warren-commission','marina-oswald'], ['warren-commission'], [], 3),
  ('tl-1964-09-24-wc-report', date '1964-09-24', null,
   'Warren Commission Report delivered to LBJ',
   'Chief Justice Warren delivers the Commission\'s 888-page final report to President Johnson. The report is released publicly September 27, 1964.',
   'investigation', ['warren-commission'], ['warren-commission'],
   ['https://www.archives.gov/research/jfk/warren-commission-report'], 5),
  ('tl-1964-11-23-wc-hearings-published', date '1964-11-23', null,
   'Warren Commission Hearings published',
   'The 26 volumes of Warren Commission Hearings and Exhibits are published through the Government Printing Office.',
   'investigation', ['warren-commission'], ['warren-commission'], [], 3),
  ('tl-1965-11-08-kilgallen-death', date '1965-11-08', null,
   'Death of Dorothy Kilgallen',
   'Journalist Dorothy Kilgallen, who interviewed Jack Ruby during his 1964 trial, is found dead in her New York home. The medical examiner rules the cause of death acute ethanol and barbiturate intoxication.',
   'death', ['ruby'], [], [], 2),
  ('tl-1966-10-05-ruby-conviction-reversed', date '1966-10-05', null,
   'Jack Ruby\'s conviction reversed',
   'The Texas Court of Criminal Appeals reverses Jack Ruby\'s 1964 conviction for the murder of Lee Harvey Oswald, citing improperly admitted testimony and prejudicial trial venue.',
   'investigation', ['ruby'], [], [], 3),
  ('tl-1967-01-03-ruby-dies', date '1967-01-03', null,
   'Death of Jack Ruby',
   'Jack Ruby dies at Parkland Memorial Hospital of a pulmonary embolism during treatment for lung cancer. He had been awaiting retrial following the October 1966 reversal.',
   'death', ['ruby'], [], [], 4),
  ('tl-1968-01-01-clark-panel', date '1968-01-01', null,
   'Clark Panel review of autopsy evidence',
   'A four-member medical panel convened by Attorney General Ramsey Clark reviews the Kennedy autopsy materials and concludes the findings are consistent with the Warren Commission\'s.',
   'investigation', [], [], [], 2),
  ('tl-1975-06-19-giancana-killed', date '1975-06-19', null,
   'Sam Giancana killed',
   'Chicago organized-crime figure Sam Giancana is shot and killed in his Oak Park, Illinois, home shortly before he is scheduled to testify before the Church Committee.',
   'death', [], [], [], 2),
  ('tl-1975-06-30-rockefeller-commission', date '1975-06-30', null,
   'Rockefeller Commission Report',
   'The Commission on CIA Activities within the United States (Rockefeller Commission) issues its report, which includes a limited review of the Kennedy assassination autopsy materials.',
   'investigation', ['cia'], [], [], 2),
  ('tl-1976-04-23-church-report', date '1976-04-23', null,
   'Church Committee final report',
   'The Senate Select Committee to Study Governmental Operations with Respect to Intelligence Activities (Church Committee) publishes its final report in six books. Book V focuses specifically on the intelligence agencies\' performance in the Kennedy investigation.',
   'investigation', [], [],
   ['https://www.intelligence.senate.gov/resources/intelligence-related-commissions'], 4),
  ('tl-1976-05-04-roselli-found', date '1976-05-04', null,
   'Johnny Roselli body found',
   'The body of CIA-mob intermediary Johnny Roselli is found in an oil drum in Dumfoundling Bay, Florida, after he had testified to the Church Committee on CIA-mafia plots against Castro.',
   'death', ['cia'], [], [], 2),
  ('tl-1976-09-17-hsca-established', date '1976-09-17', null,
   'HSCA established',
   'The U.S. House of Representatives passes House Resolution 1540 establishing the House Select Committee on Assassinations to re-examine the Kennedy and King assassinations.',
   'investigation', ['hsca'], ['hsca'], [], 4),
  ('tl-1977-03-29-demohrenschildt-death', date '1977-03-29', null,
   'Death of George de Mohrenschildt',
   'George de Mohrenschildt, who befriended the Oswalds in Dallas in 1962-63 and testified before the Warren Commission, dies in Manalapan, Florida. The medical examiner rules the death a suicide by shotgun wound. HSCA investigator Gaeton Fonzi had attempted to interview him that afternoon.',
   'death', ['oswald'], [], [], 3),
  ('tl-1978-12-29-hsca-acoustic', date '1978-12-29', null,
   'HSCA acoustic finding announced',
   'The HSCA announces a tentative acoustic finding, based on an analysis of a Dallas Police Department dictabelt recording, suggesting a fourth shot was fired. This becomes the primary basis for its "probable conspiracy" conclusion.',
   'investigation', ['hsca'], ['hsca'], [], 4),
  ('tl-1979-03-29-hsca-report', date '1979-03-29', null,
   'HSCA Final Report published',
   'The HSCA publishes its Final Report, concluding that President Kennedy was "probably assassinated as a result of a conspiracy." Twelve volumes of appendices follow.',
   'investigation', ['hsca'], ['hsca'],
   ['https://www.archives.gov/research/jfk/select-committee-report'], 5),
  ('tl-1982-05-14-nas-ramsey', date '1982-05-14', null,
   'NAS/Ramsey Panel rejects acoustic finding',
   'The National Academy of Sciences (Committee on Ballistic Acoustics, chaired by Norman Ramsey) issues a report concluding that the acoustic evidence does not support the HSCA\'s finding of a second gunman.',
   'investigation', ['hsca'], ['hsca'], [], 4),
  ('tl-1988-03-28-doj-decline', date '1988-03-28', null,
   'DOJ declines to reopen investigation',
   'The U.S. Department of Justice, in a letter to the Speaker of the House, declines to reopen its investigation of the Kennedy assassination, citing the NAS/Ramsey Panel findings.',
   'investigation', [], ['hsca'], [], 3),
  ('tl-1991-12-18-jfk-film', date '1991-12-18', null,
   'Oliver Stone\'s "JFK" released',
   'The theatrical release of Oliver Stone\'s "JFK" brings renewed public attention to the Kennedy assassination records and creates political momentum for what becomes the JFK Records Act.',
   'investigation', [], [], [], 2),
  ('tl-1992-10-26-jfk-act', date '1992-10-26', null,
   'President John F. Kennedy Assassination Records Collection Act signed',
   'President George H. W. Bush signs the JFK Records Act (P.L. 102-526), creating the JFK Assassination Records Collection at NARA and the Assassination Records Review Board (ARRB) to oversee declassification.',
   'release', [], [], [], 5),
  ('tl-1994-04-11-arrb-sworn', date '1994-04-11', null,
   'ARRB members sworn in',
   'The five members of the Assassination Records Review Board are sworn in, beginning formal declassification review.',
   'investigation', [], [], [], 2),
  ('tl-1997-04-24-zapruder-taken', date '1997-04-24', null,
   'Zapruder film declared an assassination record',
   'The ARRB formally declares the original Zapruder film an assassination record, beginning the process by which the federal government acquires it from the Zapruder family.',
   'release', [], [], [], 3),
  ('tl-1998-09-30-arrb-report', date '1998-09-30', null,
   'ARRB Final Report published',
   'The Assassination Records Review Board publishes its Final Report, concluding its work and transferring its records to the National Archives. Over 4 million pages have been declassified under the JFK Records Act by this point.',
   'release', [], [],
   ['https://www.archives.gov/research/jfk/review-board/report'], 4),
  ('tl-2017-07-24-release-1', date '2017-07-24', null,
   'JFK Records 2017 release',
   'NARA releases 3,810 documents under the JFK Records Act. Additional releases follow across 2017-2018.',
   'release', [], [], [], 3),
  ('tl-2018-04-26-release-2', date '2018-04-26', null,
   'JFK Records April 2018 release',
   'NARA releases 19,045 additional documents. This release is indexed in the current corpus under release_set=\'2017-2018\'.',
   'release', [], [], [], 3),
  ('tl-2021-12-15-release-3', date '2021-12-15', null,
   'JFK Records December 2021 release',
   'NARA releases 1,491 additional documents. Indexed as release_set=\'2021\'.',
   'release', [], [], [], 3),
  ('tl-2022-12-15-release-4', date '2022-12-15', null,
   'JFK Records December 2022 release',
   'NARA releases ~13,200 additional documents. Indexed as release_set=\'2022\'.',
   'release', [], [], [], 3),
  ('tl-2023-06-27-release-5', date '2023-06-27', null,
   'JFK Records June 2023 release',
   'NARA releases the bulk of remaining previously-withheld records per President Biden\'s October 2022 memorandum. Indexed as release_set=\'2023\'.',
   'release', [], [], [], 3),
  ('tl-2025-01-23-eo-14176', date '2025-01-23', null,
   'Executive Order 14176 signed',
   'President Trump signs Executive Order 14176 directing full release of remaining JFK-related records. The order sets a 15-day review deadline for a declassification plan.',
   'release', [], [], [], 4),
  ('tl-2025-03-18-release-6a', date '2025-03-18', null,
   'JFK Records 2025 release (March 18 drop)',
   'NARA publishes the first tranche of EO 14176 records: approximately 63,000 pages. Re-releases of many previously-redacted documents without redaction.',
   'release', [], [], [], 5),
  ('tl-2025-03-26-release-6b', date '2025-03-26', null,
   'JFK Records 2025 release (March 26 drop)',
   'Second 2025 tranche from NARA: approximately 14,000 additional pages.',
   'release', [], [], [], 4),
  ('tl-2025-04-03-release-6c', date '2025-04-03', null,
   'JFK Records 2025 release (April 3 drop)',
   'Third 2025 tranche from NARA: approximately 2,400 additional pages.',
   'release', [], [], [], 3),
  ('tl-2026-01-30-release-7', date '2026-01-30', null,
   'JFK Records January 2026 release',
   'NARA publishes 140 PDFs totaling 11,022 pages. Pending manifest and ingest.',
   'release', [], [], [], 4)
]);
